---
description: 'Deploy device plugins'

parameters:
  generic:
    description: 'Deploy generic device plugin'
    type: Boolean
    default: true

steps:
  - description: 'Install generic device plugin'
    plan: 'nest::kubernetes::deploy'
    parameters:
      service: 'generic-device-plugin'
      app: 'generic-device-plugin'
      chart: 'oci://ghcr.io/gabe565/charts/generic-device-plugin'
      namespace: 'kube-system'
      version: '0.1.3'
      wait: true
      deploy: $generic
